### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by tricknotes** [seanpdoyle/ember-cli-rails-assets#17]
Any released versions of ember-cli-rails-assets don't work  with Rails 7.
To work with Rails7, https://github.com/seanpdoyle/ember-cli-rails-assets/pull/14 is required.

@seanpdoyle 
Could you release a new version?
If you add me to GitHub / RubyGems collaborator, I'll do it.

**Comment by seanpdoyle** [comment]
Version [0.7.0](https://rubygems.org/gems/ember-cli-rails-assets) has been released.
