### ISSUE TITLE
Requiring <base> tag affects whole page

### ISSUE THREAD

**Issue by jboler** [seanpdoyle/ember-cli-rails-assets#6]
Adding a `<base href="/">` tag to `<head>` affects relative URLs for the whole page. This includes breaking [SVG `<defs>` fill URLs](http://tutorials.jenkov.com/svg/fill-patterns.html) and `<a href="#top">` style page anchors as well. This seems like an unacceptable side effect when the goal is only to have an absolute URL for the Ember asset paths.

Would it be possible to just add a secondary argument to `include_ember_script_tags()` to pass in the base path?

**Comment by jboler** [comment]
https://github.com/seanpdoyle/ember-cli-rails-assets/pull/7

**Comment by seanpdoyle** [comment]
Fixed by https://github.com/seanpdoyle/ember-cli-rails-assets/commit/23f9425dda1e4d6c0d50c22de6330743ed4489d2.
